# Generated by Django 4.0.1 on 2022-04-03 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weightlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='kg',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='weight',
            name='note',
            field=models.TextField(blank=True, help_text='Personal notes', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='weight',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
