# Generated by Django 4.0.1 on 2022-04-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightlog', '0002_weight_kg_alter_weight_note_alter_weight_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weight',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='weight',
            name='note',
        ),
    ]
