# Generated by Django 4.0.1 on 2022-04-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightlog', '0003_alter_weight_options_remove_weight_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
